name: Backend Deployment to Dockerhub
on:
  push:
    branches:
      - "develop"
    paths:
      - "backend/**"

jobs:
  verify:
    name: Audit & lint affected projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node_modules
        id: node_modules_cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Debug cache hit
        run: echo ${{ steps.node_modules_cache.outputs.cache-hit }}

      - name: Npm audit
        continue-on-error: true
        run: |
          cd backend
          npm audit --audit-level=critical --omit=dev

      - name: Npm install
        if: steps.node_modules_cache.outputs.cache-hit != 'true' # Skip if cache hit
        run: |
          cd backend
          npm i --legacy-peer-deps

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.base_ref}}

      - name: Lint affected projects
        run: |
          cd backend
          NX_BRANCH=${{ github.head_ref }} npx nx affected:lint --parallel --base=$NX_BASE --head=$NX_HEAD

  build_matrix:
    name: Export affected projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch information about branches and commits
        run: git fetch origin main

      - name: Cache node_modules
        id: node_modules_cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Npm install
        if: steps.node_modules_cache.outputs.cache-hit != 'true' # Skip if cache hit
        run: |
          cd backend
          npm i --legacy-peer-deps

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.base_ref}}

      - name: Output affected projects in nx workspace and output array
        id: set-matrix
        run: |
          cd backend
          MATRIX=(`./node_modules/.bin/nx show projects --base=$NX_BASE --head=$NX_HEAD --affected |
          tr '\n' ' '`)
          echo "::set-output name=matrix::$(jq --compact-output --null-input '$ARGS.positional' --args "${MATRIX[@]}")"

      - name: Debug variables
        run: |
          echo matrix: ${{ steps.set-matrix.outputs.matrix }}
          echo nx base tag: $NX_BASE
          echo nx head tag: $NX_HEAD

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test:
    name: Test affected projects
    needs: [build_matrix]
    if: ${{ !contains(needs.build_matrix.outputs.matrix , '[]') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node_modules
        id: node_modules_cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Npm install
        if: steps.node_modules_cache.outputs.cache-hit != 'true' # Skip if cache hit
        run: |
          cd backend
          npm i --legacy-peer-deps

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.base_ref}}

      - name: Test affected projects
        run: |
          cd backend
          NX_BRANCH=${{ github.head_ref }} npx nx run ${{ matrix.project }}:test --parallel --silent

  build:
    name: Build and deploy
    needs: [test, verify]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.11.1 LTS version
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Cache node_modules
        id: node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules

      - name: Npm install
        if: steps.node_modules.outputs.cache-hit != 'true' # Skip if cache hit
        run: cd backend && npm i --legacy-peer-deps

      - name: Build backend
        run: cd backend && npm run build

      - name: Get commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t tilloh/tilloh-dev-backend:latest -t tilloh/tilloh-dev-backend:${{ steps.vars.outputs.sha_short }} -f Backend.Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push tilloh/tilloh-dev-backend:${{ steps.vars.outputs.sha_short }}
          docker push tilloh/tilloh-dev-backend:latest